kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# This server profile used as basis for ping-devop kubernetes info

#-------------------------------------------------------------------------------------
#- Ping Identity PingDelegator getting started demo
#-
#-                          +---------------+
#-                          | PingDelegator |
#-                          +---------------+
#-
#- Setup a port-forward on port 6443 to the pingdelegator service:
#-
#-    kubectl port-forward service/pingdelegator 6443
#-
#- To view PingData Console goto:
#- 
#-    http://localhost:6443/
#-    
#- Note: Does require a pingdirectory and pingfederate instance running
#-------------------------------------------------------------------------------------

resources:
- pingdelegator.yaml
