apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdelegator
  name: pingdelegator
spec:
  ports:
  - name: https
    port: 6443
  selector:
    role: pingdelegator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdelegator
  name: pingdelegator
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdelegator
  template:
    metadata:
      labels:
        role: pingdelegator
      name: pingdelegator
    spec:
      containers:
      - image: pingidentity/pingdelegator:edge
        name: pingdelegator
        ports:
        - containerPort: 6443
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
